[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
ulp_macro = { path = "../ulp_macro" }
panic-halt = "0.2"
esp32-hal = "0.11.0"
esp32 = "0.23.0"
esp-println = { version = "0.5.0", features = ["esp32"] }
