[package]
name = "ulp_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
bitfield = "0.14.0"
proc-macro2 = "1.0"
litrs = "0.4.0"
peg = "0.8.1"

[dev-dependencies]
ariadne = "0.2.0"
