[package]
name = "ulp_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
bitfield = "0.13.2"
proc-macro2 = "1.0"
litrs = "0.2.3"
peg = "0.7.0"

[dev-dependencies]
ariadne = "0.1.3"
